# Generated by Django 4.2.10 on 2024-02-12 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(default='', max_length=50, unique=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('uni_id', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Academicyear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_no', models.CharField(max_length=100)),
                ('no_of_students', models.IntegerField(blank=True, null=True)),
                ('from_roll', models.CharField(blank=True, max_length=50, null=True)),
                ('to_roll', models.CharField(blank=True, max_length=50, null=True)),
                ('aca_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_academic_year', to='api.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('section', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('dob', models.DateField(default=None)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('guardian', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('permanent_add', models.CharField(max_length=1000)),
                ('present_add', models.CharField(max_length=1000)),
                ('transport', models.CharField(max_length=100)),
                ('hostler', models.CharField(default='', max_length=100)),
                ('ten_board', models.CharField(max_length=100)),
                ('ten_school', models.CharField(max_length=100)),
                ('ten_cgpa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inter_board', models.CharField(max_length=100)),
                ('inter_clg', models.CharField(max_length=100)),
                ('inter_cgpa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diplomo_board', models.CharField(max_length=100)),
                ('diplomo_clg', models.CharField(max_length=100)),
                ('dimplomo_cgpa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quota', models.CharField(max_length=100)),
                ('ecet_eamcet_rank', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tot_backlogs', models.IntegerField(blank=True, null=True)),
                ('aca_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='api.academicyear')),
                ('batch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_s', to='api.batch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_branch', to='api.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sgpa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('backlogs', models.PositiveIntegerField(default=0)),
                ('backlog_list', models.TextField(blank=True)),
                ('sem_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_sem', to='api.semester')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Issues_remarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remark', models.TextField(blank=True)),
                ('economic', models.TextField(blank=True)),
                ('family', models.TextField(blank=True)),
                ('teenage', models.TextField(blank=True)),
                ('health', models.TextField(blank=True)),
                ('emotional', models.TextField(blank=True)),
                ('psychological', models.TextField(blank=True)),
                ('Additional', models.TextField(blank=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counsellor_issue', to=settings.AUTH_USER_MODEL)),
                ('sem_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_sem', to='api.semester')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_student', to='api.student')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_branch', to='api.branch'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('attended', models.IntegerField()),
                ('conducted', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reasons', models.CharField(max_length=100)),
                ('medical_certificate', models.CharField(max_length=100)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metnor_attendance', to=settings.AUTH_USER_MODEL)),
                ('sem_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esm_attendance', to='api.semester')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.student')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='batch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_m', to='api.batch'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
